<?xml version="1.0"?>
<!-- HW3 -->
<robot name="object" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> 					
  <xacro:property name="box_length" value="0.2" /> 			
  <xacro:property name="box_height" value="0.05" /> 		
  <xacro:property name="cylinder_height" value="0.06" /> 	
  <xacro:property name="cylinder_radius" value="0.02" /> 	
  <xacro:property name="object_center" value="0.0" /> 		

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find scara_gazebo)/scara_description/urdf/object.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find scara_gazebo)/scara_description/urdf/materials.xacro" />


  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed_obj" type="floating">
    <parent link="world"/>
    <child link="obj_box"/>
  </joint>

  <!-- Box Object -->
  <link name="obj_box">
    <collision>
      <origin xyz="${object_center} 0 0" rpy="0 0 0"/>
      <geometry>
	       <box size="${box_length} ${box_length} ${box_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${object_center} 0 0" rpy="0 0 0"/>
      <geometry>
	       <box size="${box_length} ${box_length} ${box_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${object_center} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    	  ixx="1.0" ixy="0.0" ixz="0.0"
    	  iyy="1.0" iyz="0.0"
    	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="box_cylinder1_joint" type="fixed">
    <parent link="obj_box"/>
    <child link="obj_cylinder1"/>
  </joint>

  <joint name="box_cylinder2_joint" type="fixed">
    <parent link="obj_box"/>
    <child link="obj_cylinder2"/>
  </joint>

  <joint name="box_cylinder3_joint" type="fixed">
    <parent link="obj_box"/>
    <child link="obj_cylinder3"/>
  </joint>

  <joint name="box_cylinder4_joint" type="fixed">
    <parent link="obj_box"/>
    <child link="obj_cylinder4"/>
  </joint>


  <!-- Cylinders on the box -->
  <link name="obj_cylinder1">
    <collision>
      <origin xyz="${object_center - (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${object_center - (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="${object_center - (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="obj_cylinder2">
    <collision>
      <origin xyz="${object_center + (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${object_center + (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
      <material name="purple"/>
    </visual>

    <inertial>
      <origin xyz="${object_center + (box_length/4)} ${object_center + (box_length/4)} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="obj_cylinder3">
    <collision>
      <origin xyz="${object_center + (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${object_center + (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
         <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <origin xyz="${object_center + (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <link name="obj_cylinder4">
    <collision>
      <origin xyz="${object_center - (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${object_center - (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${cylinder_height}" radius="${cylinder_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="${object_center - (box_length/4)} ${object_center - (box_length/4)} 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

</robot>
