<?xml version="1.0"?>
<!-- RRP Manipulator -->
<robot name="scara" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="0.2" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height1_offset" value="0.25" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.35" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.25" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="${width/2}" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find scara-gazebo)/scara_description/urdf/scara.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find scara-gazebo)/scara_description/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <!-- Base Rev Joint1 -->
  <joint name="joint1" type="revolute">
    <parent link="world"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="1.0" lower="${-pi/2}" upper="${pi/2}" />
    <dynamics damping="0.7"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    	  ixx="1.0" ixy="0.0" ixz="0.0"
          iyx="0.0" iyy="1.0" iyz="0.0"
          izx="0.0" izy="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- For offset link -->
  <joint name="joint1_offset" type="fixed">
    <parent link="link1"/>
    <child link="link1_offset"/>
    <origin xyz="0 0 ${height1 + axel_offset}" rpy="0 0 0"/>
  </joint>

  <!-- Offset Link -->
  <link name="link1_offset">
    <collision>
      <origin xyz="0 ${height1_offset/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height1_offset}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${height1_offset/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height1_offset}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${height1_offset/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyx="0.0" iyy="1.0" iyz="0.0"
          izx="1.0" izy="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- Middle Rev Joint2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1_offset"/>
    <child link="link2"/>
    <origin xyz="0 ${height1_offset/2 - axel_offset} ${axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="1.0" lower="-${pi/2}" upper="${pi/2}" />
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 ${height1_offset/2 + height2/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 ${height1_offset/2 + height2/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 ${height1_offset/2 + height2/2 - axel_offset} 0" rpy="${-pi/2} 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyx="0.0" iyy="1.0" iyz="0.0"
          izx="1.0" izy="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- Final Prismatic Joint3 -->
  <joint name="joint3" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${height2 + axel_offset/2} 0" rpy="${pi} 0 0"/>
    <!-- Limits are from the link origin and not the joint origins -->
    <!-- limit effort="30" velocity="1.0" upper="${-height3/2 + axel_offset}" lower="${height3 - 2*axel_offset}" /-->
    <limit effort="30" velocity="1.0" lower="0" upper="${-height3/2 + axel_offset}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Final Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${-height3/2 + axel_offset}" rpy="0 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${-height3/2 + axel_offset}" rpy="0 0 0"/>
      <geometry>
          <box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${-height3/2 + axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyx="0.0" iyy="1.0" iyz="0.0"
          izx="1.0" izy="0.0" izz="1.0"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
