# Robot Configurations ---------------------------------------

scara:
  link_lengths: {
                    L1: 1.3,
                    L2: 0.5,
                    L3: 0.5,
                    L4: 0.4
                }

  link_masses: {
                    m1: 0.2,
                    m2: 0.2,
                    m3: 0.2,
                    m4: 0.1
               }

  link_width: 0.1
